name: Publish npm

on:
  release:
    types: [created]

jobs:
  package:
    name: "Create Package"
    runs-on: ubuntu-20.04
    permissions: 
      contents: read
      packages: write 
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"

  publish:
    if: github.ref == 'refs/heads/master'
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-20.04
    steps:
    - name: Get package
      uses: actions/download-artifact@v2
      with:
        name: package
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup -node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@digitalspace'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
