name: Publish npm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pr:
    name: pr
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and run build
        run: |
          npm i
          npm run build
        env:
          CI: true

      - name: Get version
        run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      
      - name: Make npm package
        run: npm pack
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"
    
    publish:
      name: "Publish to GitHub Packages"
      needs: [package]
      runs-on: ubuntu-18.04
      steps:
      - name: Upload
        uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: "@digitalspace"
      - run: echo "registry=https://npm.pkg.github.com/@digitalspace" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
